### ISSUE TITLE
SSL Certificate Verification Error !

### ISSUE THREAD

**Issue by nazi98** [charlyie/resmushit-wordpress#10]
OpenSSL Error - ssl verification failed :
**cannot enable crypto on "file_get_contents($json->dest)" line 92 "resmushit.class.php"**

Temp solution :

Add this Array **before $data**
$arrContextOptions= array("ssl" => array("verify_peer" => false,"verify_peer_name" => false));

Replace **"$data = file_get_contents($json->dest)"** with 
**"$data = file_get_contents( $json->dest, false, stream_context_create($arrContextOptions) );"**

Tested Plugin version : **0.4.3**

Is there any **Stable** solution to fix this bug ?

**Comment by charlyie** [comment]
OK, it was fixed on server side, we'll deliver a new release soon which will include a certification failure management. Thanks for the report!

**Comment by charlyie** [comment]
Well, it has been definitely fixed in today's release. Thanks :)
