### ISSUE TITLE
RESMUSHIT_QLTY is not defined

### ISSUE THREAD

**Issue by mickaelperrin** [charlyie/resmushit-wordpress#4]
Hi,

Jus to inform you, that the `RESMUSHIT_QLTY ` is not defined in your code.

https://github.com/charlyie/resmushit-wordpress/blob/3c7ed95a2ebfb303a75892b407667daf533744ef/classes/resmushit.class.php#L37

and throws the following warning:

```
Warning: Use of undefined constant RESMUSHIT_QLTY - assumed 'RESMUSHIT_QLTY' (this will throw an Error in a future version of PHP)
```

It would be good to provide a default value:

```php
if (!defined('RESMUSHIT_QLTY') {
  define('RESMUSHIT_QLTY', 'XXXX');
}
```

Thanks

**Comment by airplanenoise** [comment]
another reason to do that is that depending on your server config and the size of your media library on initial smush, the error log file gets huge and that can lead to issues... like disk full and such, just went through that myself.

**Comment by charlyie** [comment]
Hi, your commit has been added to our last release 0.1.23 :)
Thanks for this help,
Cheers,
Charles
