### ISSUE TITLE
Add settings link from "All plugins page"

### ISSUE THREAD

**Issue by jasomdotnet** [charlyie/resmushit-wordpress#5]
[Here](https://salferrarello.com/wordpress-plugin-add-settings-link/) is a link how to add 'settings' link from "All plugins page" (`wp-admin/plugins.php`). It's important to new plugin users to let them know that plugin has also configuration page.

**Comment by charlyie** [comment]
Hi, your commit has been added to our last release 0.1.23 :)
Thanks for this help,
Cheers,
Charles
